require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('./models/Product');

const books = [
  {
    title: 'El Señor de los Anillos',
    author: 'J.R.R. Tolkien',
    description: 'La épica historia de la Tierra Media donde una pequeña comunidad debe destruir el Anillo Único para salvar el mundo de la oscuridad eterna. Una obra monumental de la literatura fantástica.',
    price: 54900, originalPrice: 65000,
    cover: 'https://covers.openlibrary.org/b/id/8743101-L.jpg',
    category: 'Fantasy', rating: 4.9, reviews: 12847, pages: 1178,
    bookLanguage: 'Español', publisher: 'Minotauro', publishedYear: 1954,
    featured: true, bestseller: true,
    tags: ['tolkien', 'épico', 'elfos', 'anillo'],
  },
  {
    title: 'Harry Potter y la piedra filosofal',
    author: 'J.K. Rowling',
    description: 'Harry descubre que es un mago y entra al Colegio Hogwarts donde aprende magia, hace amigos y descubre su verdadero destino en el mundo mágico.',
    price: 31900,
    cover: 'https://covers.openlibrary.org/b/id/10110415-L.jpg',
    category: 'Fantasy', rating: 4.9, reviews: 45678, pages: 309,
    bookLanguage: 'Español', publisher: 'Salamandra', publishedYear: 1997,
    featured: true, bestseller: true,
    tags: ['magia', 'hogwarts', 'rowling'],
  },
  {
    title: 'Dune',
    author: 'Frank Herbert',
    description: 'En el planeta desértico Arrakis, Paul Atreides se convierte en el líder de los Fremen en una épica historia de política, religión y ecología galáctica.',
    price: 38900,
    cover: 'https://covers.openlibrary.org/b/id/12818862-L.jpg',
    category: 'Sci-Fi', rating: 4.8, reviews: 9234, pages: 896,
    bookLanguage: 'Español', publisher: 'Debolsillo', publishedYear: 1965,
    featured: true, bestseller: true,
    tags: ['desierto', 'futuro', 'política'],
  },
  {
    title: 'Fundación',
    author: 'Isaac Asimov',
    description: 'Hari Seldon predice la caída del Imperio Galáctico e intenta preservar el conocimiento de la humanidad para reducir la inevitable era de oscuridad.',
    price: 33900,
    cover: 'https://covers.openlibrary.org/b/id/8224161-L.jpg',
    category: 'Sci-Fi', rating: 4.7, reviews: 11234, pages: 296,
    bookLanguage: 'Español', publisher: 'Debolsillo', publishedYear: 1951,
    featured: true,
    tags: ['asimov', 'galaxia', 'futuro'],
  },
  {
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    description: 'Un recorrido fascinante por la historia de la humanidad, desde los primeros humanos hasta la revolución cognitiva y la era moderna.',
    price: 42900,
    cover: 'https://covers.openlibrary.org/b/id/10720836-L.jpg',
    category: 'History', rating: 4.7, reviews: 21450, pages: 498,
    bookLanguage: 'Español', publisher: 'Debate', publishedYear: 2011,
    featured: true, bestseller: true,
    tags: ['historia', 'humanidad', 'ciencia'],
  },
  {
    title: 'Atomic Habits',
    author: 'James Clear',
    description: 'El método probado para crear buenos hábitos y eliminar los malos. Un sistema simple y comprobado para transformar radicalmente tu vida.',
    price: 47900,
    cover: 'https://covers.openlibrary.org/b/id/12628161-L.jpg',
    category: 'Self-Help', rating: 4.8, reviews: 32100, pages: 320,
    bookLanguage: 'Español', publisher: 'Planeta', publishedYear: 2018,
    featured: true, bestseller: true, newRelease: true,
    tags: ['hábitos', 'productividad', 'psicología'],
  },
  {
    title: 'Clean Code',
    author: 'Robert C. Martin',
    description: 'El libro definitivo para escribir código limpio, mantenible y profesional. Una guía esencial para todo desarrollador de software moderno.',
    price: 89900,
    cover: 'https://covers.openlibrary.org/b/id/10521526-L.jpg',
    category: 'Technology', rating: 4.6, reviews: 7845, pages: 431,
    bookLanguage: 'Inglés', publisher: 'Prentice Hall', publishedYear: 2008,
    featured: true,
    tags: ['programación', 'código', 'software'],
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'David Thomas & Andrew Hunt',
    description: 'Consejos prácticos de dos expertos que transformarán tu forma de programar y pensar sobre el desarrollo de software.',
    price: 79900, originalPrice: 95000,
    cover: 'https://covers.openlibrary.org/b/id/13293939-L.jpg',
    category: 'Technology', rating: 4.7, reviews: 6543, pages: 352,
    bookLanguage: 'Inglés', publisher: 'Addison-Wesley', publishedYear: 1999,
    tags: ['programación', 'carrera', 'buenas prácticas'],
  },
  {
    title: 'Cien años de soledad',
    author: 'Gabriel García Márquez',
    description: 'La saga de la familia Buendía en el mítico pueblo de Macondo. La obra cumbre del realismo mágico latinoamericano, Premio Nobel de Literatura.',
    price: 34900,
    cover: 'https://covers.openlibrary.org/b/id/8254434-L.jpg',
    category: 'Classic', rating: 4.6, reviews: 18234, pages: 432,
    bookLanguage: 'Español', publisher: 'Real Academia Española', publishedYear: 1967,
    bestseller: true,
    tags: ['realismo mágico', 'colombia', 'García Márquez'],
  },
  {
    title: '1984',
    author: 'George Orwell',
    description: 'Una distopía perturbadora sobre un futuro totalitario donde el Gran Hermano todo lo ve y la libertad de pensamiento es el mayor crimen posible.',
    price: 29900, originalPrice: 35000,
    cover: 'https://covers.openlibrary.org/b/id/8575708-L.jpg',
    category: 'Classic', rating: 4.7, reviews: 15623, pages: 328,
    bookLanguage: 'Español', publisher: 'Debolsillo', publishedYear: 1949,
    bestseller: true,
    tags: ['distopía', 'política', 'clásico'],
  },
  {
    title: 'El Principito',
    author: 'Antoine de Saint-Exupéry',
    description: 'El clásico atemporal sobre un pequeño príncipe que viaja por el universo y aprende lecciones sobre la vida, el amor y lo que verdaderamente importa.',
    price: 24900, originalPrice: 28000,
    cover: 'https://covers.openlibrary.org/b/id/14625765-L.jpg',
    category: 'Classic', rating: 4.8, reviews: 28934, pages: 96,
    bookLanguage: 'Español', publisher: 'Salamandra', publishedYear: 1943,
    bestseller: true,
    tags: ['clásico', 'filosofía', 'amor'],
  },
  {
    title: 'El código Da Vinci',
    author: 'Dan Brown',
    description: 'El profesor Langdon se ve envuelto en una conspiración que involucra el mayor secreto de la historia cristiana y una peligrosa cacería mortal.',
    price: 36900,
    cover: 'https://covers.openlibrary.org/b/id/8752474-L.jpg',
    category: 'Mystery', rating: 4.4, reviews: 34521, pages: 489,
    bookLanguage: 'Español', publisher: 'Planeta', publishedYear: 2003,
    bestseller: true,
    tags: ['conspiración', 'religión', 'thriller'],
  },
  {
    title: 'Orgullo y prejuicio',
    author: 'Jane Austen',
    description: 'La historia inmortal de Elizabeth Bennet y el señor Darcy. Una novela que explora el amor, el matrimonio y la sociedad inglesa del siglo XIX.',
    price: 27900,
    cover: 'https://covers.openlibrary.org/b/id/8739161-L.jpg',
    category: 'Romance', rating: 4.7, reviews: 22145, pages: 432,
    bookLanguage: 'Español', publisher: 'Alba', publishedYear: 1813,
    tags: ['austen', 'clásico', 'victoriano'],
  },
  {
    title: 'Zero to One',
    author: 'Peter Thiel',
    description: 'El cofundador de PayPal explica cómo construir startups que crean algo verdaderamente nuevo y cómo pensar de forma singular sobre el futuro.',
    price: 52900,
    cover: 'https://covers.openlibrary.org/b/id/9109397-L.jpg',
    category: 'Business', rating: 4.5, reviews: 9876, pages: 224,
    bookLanguage: 'Español', publisher: 'Península', publishedYear: 2014,
    newRelease: true,
    tags: ['startups', 'innovación', 'tecnología'],
  },
  {
    title: 'Steve Jobs',
    author: 'Walter Isaacson',
    description: 'La biografía autorizada del cofundador de Apple, basada en más de cuarenta entrevistas con Jobs, su familia, amigos y rivales más cercanos.',
    price: 59900, originalPrice: 69900,
    cover: 'https://covers.openlibrary.org/b/id/8739341-L.jpg',
    category: 'Biography', rating: 4.5, reviews: 15678, pages: 656,
    bookLanguage: 'Español', publisher: 'Debate', publishedYear: 2011,
    tags: ['apple', 'tecnología', 'innovación'],
  },
  {
    title: 'La sombra del viento',
    author: 'Carlos Ruiz Zafón',
    description: 'Barcelona, 1945. Un niño descubre un misterioso libro que lo llevará por un laberinto de intrigas y secretos oscuros que marcarán su vida.',
    price: 34900,
    cover: 'https://covers.openlibrary.org/b/id/12671937-L.jpg',
    category: 'Fiction', rating: 4.7, reviews: 11230, pages: 512,
    bookLanguage: 'Español', publisher: 'Planeta', publishedYear: 2001,
    bestseller: true,
    tags: ['barcelona', 'misterio', 'romance'],
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    await Product.deleteMany({});
    const inserted = await Product.insertMany(books);
    console.log(`✅ ${inserted.length} libros insertados correctamente en MongoDB`);
    process.exit(0);
  } catch (e) {
    console.error('❌ Error en seed:', e.message);
    process.exit(1);
  }
}

seed();
